---
- name: Setup
  ansible.builtin.include_tasks: setup_dependencies.yaml
  tags:
    - reset
    - setup
    - paperless

- name: Remove Paperless
  ansible.builtin.include_tasks: remove_paperless.yaml
  tags:
    - reset
    - remove

- name: Remove/Reset
  ansible.builtin.include_tasks: remove.yaml
  tags:
    - reset
    - remove
    - never

- name: Setup Paperless
  ansible.builtin.include_tasks: setup_paperless.yaml
  tags:
    - reset
    - setup

- name: Integration Testing
  ansible.builtin.include_tasks: integration_test.yaml
  tags:
    - test
